### ISSUE TITLE
Can't start minkube: VirtualBox is not installed on the machine

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-helm#9]
As a developer whothout any experience with minikube, I want to know what I need to have installed (and maybe how), so that I can start it easiely.

## Acceptance Criteria

- [ ] Able to start minkube following instructions from README
- [ ] Do not have to google around to start minkube server

## Tasks

- [ ] Do analysis
- [ ] Update README with instuctions if neccessary

## Analysis

As a developer I encountered the following error after installed Minkube and trying to start it as suggestetd in [README](https://github.com/ViderumGlobal/ckan-cloud-helm/blob/master/QUICKSTART_DEVELOPMENT.md#start-a-minikube-cluster)

```
minikube start --kubernetes-version "${KUBERNETES_VERSION}"
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
E1105 15:27:46.230633   25830 start.go:187] Error starting host: Error creating host: Error executing step: Running precreate checks.
: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path.

 Retrying.
E1105 15:27:46.231159   25830 start.go:193] Error starting host:  Error creating host: Error executing step: Running precreate checks.
: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
```

I had to do following to make it running

- Install virtualbox
- Include `--vm-driver` flag when starting minkube

### Install virtualbox

This tutorial hellped https://websiteforstudents.com/installing-virtualbox-5-2-ubuntu-17-04-17-10/

```
sudo apt-get update && sudo apt-get dist-upgrade && sudo apt-get autoremove
sudo apt-get -y install gcc make linux-headers-$(uname -r) dkms
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" >> /etc/apt/sources.list'
sudo apt-get update
sudo apt-get install virtualbox-5.2
```

### Run with --vm-driver=

```
minikube start --kubernetes-version "${KUBERNETES_VERSION}" --vm-driver=virtualbox
```

**Comment by akariv** [comment]
Probably would be best to refer to the official instructions at

https://kubernetes.io/docs/tasks/tools/install-minikube/

instead of rewriting a short version of those instructions in our README.
